spring.application.name=jasper
server.port=8989
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/jasper123
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

# Jasper Report Template Path
jasper.report.path=src/main/resources/reports/

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool Configuration (HikariCP, default for Spring Boot)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# Logging Configuration
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Custom Properties (if needed)
my.custom.property=value
